mocha test/unit/test.js
mocha test/unit/test_bson.js
mocha test/unit/testChain.js
mocha test/unit/testChain_more.js
mocha test/unit/testChain_more_2.js
mocha test/unit/testChainWithPass.js
mocha test/unit/testNested.js
mocha test/unit/testCopy.js
mocha test/unit/testFilter.js
sh test/tools/rmTestJsonFile.sh
